### ISSUE TITLE
Please 1. publish on Marketplace & 2. update links

### ISSUE THREAD

**Issue by peter-lyons-kehl** [codespaces-contrib/flashcode#7]
Hi Jonathan,

Thank you for `CodeTour`, `CodeSwing` and this. Please
- publish this on Marketplace, and
- update the link in https://github.com/lostintangent/lostintangent (currently https://marketplace.visualstudio.com/items?itemName=codespaces-Contrib.flashcode, which doesn't exist), and
- update https://github.com/lostintangent/flashcode > README.md to point to Marketplace, and
- update https://github.com/lostintangent/flashcode > the link on the right side (currently https://aka.ms/flashcode, which goes to Bing...).

**Comment by lostintangent** [comment]
Hey! This extension was a bit of an experiment, and I'm not sure it was ever valuable enough to publish/maintain. So I'll likely just remove it from my profile readme, as opposed to putting it in the marketplace.
